General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /etc/hyperledger/orderer/crypto-config/tls/server.key
    Certificate: /etc/hyperledger/orderer/crypto-config/tls/server.crt
    RootCAs: &ref_0
      - /etc/hyperledger/orderer/crypto-config/tlsca/tlsca.orderer-cert.pem
      - >-
        /etc/hyperledger/orderer/crypto-config/tlsca/tlsca.btp.example.com-cert.pem
    ClientAuthRequired: false
    ClientRootCAs: *ref_0
    TLSHandshakeTimeShift: 0s
  Cluster:
    ClientCertificate: /etc/hyperledger/orderer/crypto-config/tls/server.crt
    ClientPrivateKey: /etc/hyperledger/orderer/crypto-config/tls/server.key
    RootCAs: *ref_0
    DialTimeout: 5s
    RPCTimeout: 7s
    ReplicationBufferSize: 20971520
    ReplicationPullTimeout: 5s
    ReplicationRetryTimeout: 5s
    ReplicationBackgroundRefreshInterval: 5m0s
    ReplicationMaxRetries: 12
    SendBufferSize: 10
    CertExpirationWarningThreshold: 168h0m0s
    TLSHandshakeTimeShift: 0s
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  BootstrapMethod: file
  BootstrapFile: /etc/hyperledger/orderer/block/system-channel.block
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  LocalMSPDir: /etc/hyperledger/orderer/crypto-config/msp
  LocalMSPID: OrdererMSP
  BCCSP:
    ProviderName: SW
    SwOpts:
      SecLevel: 256
      HashFamily: SHA2
      Ephemeral: true
  Authentication:
    TimeWindow: 15m
    NoExpirationChecks: false
FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
Operations:
  ListenAddress: 0.0.0.0:9443
  TLS:
    Enabled: false
    PrivateKey: /etc/hyperledger/orderer/crypto-config/tls/server.key
    Certificate: /etc/hyperledger/orderer/crypto-config/tls/server.crt
    RootCAs: *ref_0
    ClientAuthRequired: false
    ClientRootCAs: *ref_0
    TLSHandshakeTimeShift: 0s
Metrics:
  Provider: disabled
ChannelParticipation:
  Enabled: false
  RemoveStorage: false
