Profiles:
  system-channelProfile:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Orderer:
      OrdererType: etcdraft
      Addresses: &ref_0
        - orderer0.example.com:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 500
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 2 MB
      MaxChannels: 0
      EtcdRaft:
        Consenters:
          - Host: orderer0.example.com
            Port: 7050
            ClientTLSCert: >-
              crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt
            ServerTLSCert: >-
              crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt
        Options:
          TickInterval: 500ms
          ElectionTick: 10
          HeartbeatTick: 1
          MaxInflightBlocks: 5
          SnapshotIntervalSize: 16 MB
      Organizations:
        - Name: OrdererMSP
          ID: OrdererMSP
          MSPDir: crypto-config/ordererOrganizations/example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("OrdererMSP.member")
            Writers:
              Type: Signature
              Rule: OR("OrdererMSP.member")
            Admins:
              Type: Signature
              Rule: OR("OrdererMSP.admin")
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitMeta
          Rule: ANY Writers
      Capabilities:
        V2_0: true
    Application:
      ACLs:
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Readers
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        peerOrgDefaultslscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetChannelConfig: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Writers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
        Endorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
      Capabilities:
        V2_0: true
      Organizations:
        - Name: OrdererMSP
          ID: OrdererMSP
          MSPDir: crypto-config/ordererOrganizations/example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("OrdererMSP.member")
            Writers:
              Type: Signature
              Rule: OR("OrdererMSP.member")
            Admins:
              Type: Signature
              Rule: OR("OrdererMSP.admin")
    Consortiums:
      Example:
        Organizations:
          - Name: btpMSP
            ID: btpMSP
            MSPDir: crypto-config/peerOrganizations/btp.example.com/msp
            Policies:
              Readers:
                Type: Signature
                Rule: OR("btpMSP.member")
              Writers:
                Type: Signature
                Rule: OR("btpMSP.member")
              Admins:
                Type: Signature
                Rule: OR("btpMSP.admin")
              Endorsement:
                Type: Signature
                Rule: OR("btpMSP.peer")
            OrdererEndpoints: *ref_0
            AnchorPeers:
              - Host: peer0.btp.example.com
                Port: 7051
