version: "3"
networks:
  default:
    external:
      name: btp
services:
  ca.btp.example.com:
    restart: always
    container_name: ca.btp.example.com
    image: docker.io/hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw-d'
    ports:
      - 7054:7054
    volumes:
      - >-
        ../artifacts/crypto-config/peerOrganizations/btp.example.com/ca:/etc/hyperledger/fabric-ca-server-crypto
      - >-
        ../config/ca.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
